version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: "Asia/Seoul"
    volumes:
      - D:/db/postgresql/data:/var/lib/postgresql/data
      - D:/db/postgresql/postgresql.conf:/etc/postgresql.conf